format_version: 3
pipelines:
  spring-app:
    group: spring-apps
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/brunooon/spring-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - package
                - -DskipTests
                command: mvn
                run_if: passed
    - unity-tests:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          unity-tests:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - package
                - -DskipTests
                command: mvn
                run_if: passed
    - publish:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          publish:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - sleep 10
                command: /bin/bash
                run_if: passed
  deploy-dev:
    group: spring-apps
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/brunooon/hello-world.git
        shallow_clone: false
        auto_update: true
        branch: master
      spring-app: 
        pipeline: spring-app
        stage: publish
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          dev:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - sleep 10
                command: /bin/bash
                run_if: passed
  deploy-ti:
    group: spring-apps
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/brunooon/hello-world.git
        shallow_clone: false
        auto_update: true
        branch: master
      spring-app: 
        pipeline: deploy-dev
        stage: deploy
      quality-check:
        pipeline: quality-check
        stage: quality-check
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          dev:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - sleep 10
                command: /bin/bash
                run_if: passed
  quality-check:
    group: spring-apps
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/brunooon/hello-world.git
        shallow_clone: false
        auto_update: true
        branch: master
      spring-app: 
        pipeline: spring-app
        stage: build
    stages:
    - quality-check:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          sonar:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - sleep 10
                command: /bin/bash
                run_if: passed
          veracode:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - sleep 10
                command: /bin/bash
                run_if: passed
