format_version: 3
pipelines:
  spring-app:
    group: spring-apps
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/brunooon/spring-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - package
                command: mvn
                run_if: passed
          unity-tests:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - package
                - -DskipTests
                command: mvn
                run_if: passed
