format_version: 3
environments:
  qa:
    pipelines:
      - hello-world
pipelines:
  hello-world:
    group: hello-world
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/brunooon/spring-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - default-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          default-job:
            resources:
              - git
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ./mvnw clean package
                command: /bin/bash
                run_if: passed
